# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stonx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stonx
   pod 'Parse'
   pod 'AlamofireImage'
   pod 'Charts'

  target 'StonxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StonxUITests' do
    # Pods for testing
  end

end
